name: Manually auto-approve PR

on:
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: 'PR number to auto-approve'
        required: true
        type: string

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
          review-message: "Auto-approved via gh workflow run"
